// packages/ui: one set of TSX (components · hooks · lib), the icon libraries in use, and one folder per system.
//
//   <ui>/src/components|hooks|lib/…            registry/ui, aliases rewritten to <scope>/ui/…
//   <ui>/src/icons/names.ts                    the semantic names
//   <ui>/src/icons/libraries/<library>.tsx     only the libraries some app uses
//   <ui>/src/icons/index.ts                    re-exports the monorepo default library (what packages/ui's tsc sees)
//   <ui>/src/icons/check.ts                    every installed library exports every name
//   <ui>/src/systems/<name>/…                  registry/systems/<name>/styles + DESIGN.md + system.json

import { existsSync } from "node:fs";
import { join, relative } from "node:path";

import { rewriteAliases } from "./source.mjs";
import { hash, posix, read, readJson, sortKeys, walk, writeFile, writeJson } from "./util.mjs";

const HEADER = (what) => `Generated by tyohnn scaffold-prototype — ${what}. Edit the registry and re-run instead of editing here.`;

export const uiPaths = (target, uiPath) =>
{
    const root = join(target, uiPath);

    return {
        root,
        src: join(root, "src"),
        pkg: join(root, "package.json"),
        systems: join(root, "src/systems"),
        icons: join(root, "src/icons"),
        library: (name) => join(root, "src/icons/libraries", `${name}.tsx`),
    };
};

/** Copies one file from the source into the target, records its hash under target-relative path */
const copy = (ctx, from, to, transform = (content) => content) =>
{
    const content = transform(read(from));

    writeFile(to, content);
    ctx.record.files[posix(relative(ctx.target, to))] = hash(content);
    ctx.log.wrote(to);
};

const mergeDependencies = (ctx, into, from) =>
{
    for (const [name, range] of Object.entries(from ?? {}))
    {
        if (into[name] && into[name] !== range) ctx.log.note(`${name}: keeping ${into[name]} (tyohnn wants ${range})`);
        else into[name] = range;
    }
};

/** The shared TSX, package.json and tsconfig of packages/ui (init only) */
export const writeUiBase = (ctx) =>
{
    const { source, scope } = ctx;
    const ui = uiPaths(ctx.target, ctx.uiPath);
    const rewrite = (content) => rewriteAliases(content, scope);

    for (const file of source.manifest.files)
    {
        if (!/^(components|hooks|lib)\//.test(file) && file !== "icons/names.ts") continue;
        copy(ctx, source.uiFile(file), join(ui.src, file), rewrite);
    }

    const pkg = readJson(ui.pkg, { name: `${scope}/ui`, version: "0.0.0", private: true });

    pkg.description ??= "shadcn components on Base UI primitives with tyohnn design systems (one set of TSX, one CSS folder per system).";
    pkg.exports = {
        "./components/*": "./src/components/*.tsx",
        "./lib/*": "./src/lib/*.ts",
        "./hooks/*": "./src/hooks/*.ts",
        "./icons": "./src/icons/index.ts",
        "./icons/names": "./src/icons/names.ts",
        ...Object.fromEntries(Object.entries(pkg.exports ?? {}).filter(([key]) => key.startsWith("./systems/"))),
    };
    pkg.scripts = { ...pkg.scripts, typecheck: "tsc --noEmit" };
    pkg.dependencies ??= {};
    pkg.devDependencies ??= {};
    mergeDependencies(ctx, pkg.dependencies, source.manifest.dependencies);
    mergeDependencies(ctx, pkg.devDependencies, { ...source.manifest.devDependencies, "@types/node": "^20" });
    writePackage(ctx, pkg);

    writeJson(join(ui.root, "tsconfig.json"), {
        extends: posix(relative(ui.root, join(ctx.target, "tsconfig.base.json"))),
        compilerOptions: {
            lib: ["ES2022", "DOM", "DOM.Iterable"],
            jsx: "react-jsx",
            types: ["node"],
            // Self-references resolve to the source; @scope/ui/icons is the monorepo default library here.
            // Each app's tsconfig points @scope/ui/icons at its own library instead.
            paths: {
                [`${scope}/ui/components/*`]: ["./src/components/*"],
                [`${scope}/ui/lib/*`]: ["./src/lib/*"],
                [`${scope}/ui/hooks/*`]: ["./src/hooks/*"],
                [`${scope}/ui/icons`]: ["./src/icons/index.ts"],
            },
        },
        include: ["src/**/*.ts", "src/**/*.tsx"],
        exclude: ["node_modules"],
    });
    ctx.log.wrote(join(ui.root, "tsconfig.json"));
};

const writePackage = (ctx, pkg) =>
{
    const ui = uiPaths(ctx.target, ctx.uiPath);

    pkg.dependencies = sortKeys(pkg.dependencies);
    pkg.devDependencies = sortKeys(pkg.devDependencies);
    writeJson(ui.pkg, pkg);
    ctx.log.wrote(ui.pkg);
};

/** Adds an icon library's mapping file and packages; rewrites icons/index.ts and check.ts */
export const addIconLibrary = (ctx, library) =>
{
    const info = ctx.source.manifest.iconLibraries[library];

    if (!info) throw new Error(`Unknown icon library "${library}" (known: ${Object.keys(ctx.source.manifest.iconLibraries).join(", ")})`);

    const ui = uiPaths(ctx.target, ctx.uiPath);
    const pkg = readJson(ui.pkg);

    copy(ctx, ctx.source.uiFile(info.file), ui.library(library), (content) => rewriteAliases(content, ctx.scope));
    mergeDependencies(ctx, pkg.dependencies, info.packages);
    writePackage(ctx, pkg);

    const libraries = [...new Set([...(ctx.record.ui.icons.libraries ?? []), library])].sort();

    ctx.record.ui.icons.libraries = libraries;
    ctx.record.ui.icons.default ??= library;

    const index = [
        `// ${HEADER("icons")}`,
        `// ${ctx.scope}/ui/icons — the monorepo default icon library (${ctx.record.ui.icons.default}): what packages/ui's own tsc resolves.`,
        "// Each app points the specifier at its own libraries/<library>.tsx (tsconfig paths + next.config resolve aliases).",
        `export * from "./libraries/${ctx.record.ui.icons.default}";`,
        "",
    ].join("\n");
    const check = [
        `// ${HEADER("icons")}`,
        "// Type-level completeness: every installed library exports every semantic name as an icon component.",
        ...libraries.map((name) => `import type * as ${name} from "./libraries/${name}";`),
        'import type { IconComponent, IconName } from "./names";',
        "",
        "type Complete<Library extends Record<IconName, IconComponent>> = Library;",
        "",
        "export type IconLibraries = {",
        ...libraries.map((name) => `    ${name}: Complete<typeof ${name}>;`),
        "};",
        "",
    ].join("\n");

    writeFile(join(ui.icons, "index.ts"), index);
    writeFile(join(ui.icons, "check.ts"), check);
    ctx.log.wrote(join(ui.icons, "index.ts"));
    ctx.log.wrote(join(ui.icons, "check.ts"));
};

/** Copies a system snapshot into src/systems/<name>/ and exports its CSS */
export const addSystem = (ctx, name) =>
{
    const { source } = ctx;
    const meta = source.systemMeta(name);
    const ui = uiPaths(ctx.target, ctx.uiPath);
    const dir = source.systemDir(name);
    const out = join(ui.systems, name);

    if (existsSync(join(out, "system.json")) && ctx.record.ui.systems.includes(name))
    {
        ctx.log.note(`system ${name} is already in ${ctx.uiPath}; re-copied from the source`);
    }

    for (const file of walk(join(dir, "styles")))
    {
        copy(ctx, file, join(out, relative(join(dir, "styles"), file)));
    }

    if (existsSync(join(dir, "DESIGN.md")))
    {
        copy(ctx, join(dir, "DESIGN.md"), join(out, "DESIGN.md"));
    }
    else if (existsSync(join(dir, "DESIGN.template.md")))
    {
        copy(ctx, join(dir, "DESIGN.template.md"), join(out, "DESIGN.md"), (content) =>
            `<!-- ${name} has no DESIGN.md of its own; this is its DESIGN.template.md. -->\n\n${content}`);
    }

    // The metadata an app needs (fonts · icons · defaultMode), whatever file the source kept it in.
    const systemJson = {
        name,
        description: meta.description,
        fonts: meta.fonts,
        icons: meta.icons,
        defaultMode: meta.defaultMode,
        ...(meta.forkedFrom ? { forkedFrom: meta.forkedFrom } : {}),
        ...(meta.tags ? { tags: meta.tags } : {}),
    };

    writeJson(join(out, "system.json"), systemJson);
    ctx.record.files[posix(relative(ctx.target, join(out, "system.json")))] = hash(`${JSON.stringify(systemJson, null, 4)}\n`);
    ctx.log.wrote(join(out, "system.json"));

    if (meta.defaultModeInferred) ctx.log.note(`${name}: system.json has no defaultMode; inferred ${meta.defaultMode}`);

    const pkg = readJson(ui.pkg);

    pkg.exports[`./systems/${name}/*.css`] = `./src/systems/${name}/*.css`;
    writePackage(ctx, pkg);

    ctx.record.ui.systems = [...new Set([...ctx.record.ui.systems, name])].sort();

    return meta;
};
