// Makes the project match tyohnn.json. Every command edits the record (which system, icons, fonts and mode each app
// has) and then calls sync, so running a command twice changes nothing the second time.
//
//   1. CLI-owned files: the shared TSX, the icon libraries in use, the systems in use, examples; unused ones removed
//   2. package.json dependencies (the UI package, and each app)
//   3. install, when a package.json changed or nothing is installed yet
//   4. each app's user-owned files, through codemods and managed blocks: entry CSS, root layout, index.html,
//      tsconfig paths, next.config / vite.config

import { dirname, join } from "node:path";

import { applyEntryCss, userCustomProperties } from "../codemods/css.js";
import { applyLayout, HTML_CLASS_IDENTIFIER, layoutBlock } from "../codemods/layout.js";
import { ensureTranspilePackage, newNextConfig } from "../codemods/next-config.js";
import { effectivePaths, setPaths } from "../codemods/tsconfig.js";
import { applyIndexHtml, applyViteConfig, ensureCssImport, type ViteAlias } from "../codemods/vite.js";
import { exists, read, readIfExists, rel, relSpecifier, writeFile } from "../lib/fs.js";
import type { Changes } from "../lib/log.js";
import type { Registry } from "../source/registry.js";
import { type AppFiles, inspectApp } from "./app.js";
import { expectedPackageDir, packageDir, type PackageJson, type PackageManager } from "./detect.js";
import { cssFontImports, familyStacks, fontPackages, nextFontCode, nextFontStacks, sameFonts, stacksCss } from "./fonts.js";
import { syncDependencies, updatePackageJson } from "./package-json.js";
import { isCode, type Placement, placementOf } from "./placement.js";
import { install, workspaceRange } from "./pm.js";
import { type AppRecord, type TyohnnRecord, usedIcons, usedSystems, writeRecord } from "./record.js";
import { isOwnTheme, themeCss } from "./theme.js";
import { OwnedFiles } from "./writer.js";

export interface SyncOptions
{
    force: boolean;
    install: boolean;
}

export interface SyncContext
{
    root: string;
    registry: Registry;
    record: TyohnnRecord;
    changes: Changes;
    options: SyncOptions;
}

const TAILWIND_RANGE = "^4";

export const SYSTEM_CSS_FILES = ["globals.css", "theme.css", "tokens.css", "typeset.css", "typeset-preset.css", "style.css"] as const;

/** The monorepo default icon library: the one most apps use (alphabetical on a tie) */
export const defaultIconLibrary = (record: TyohnnRecord): string =>
{
    const counts = new Map<string, number>();

    Object.values(record.apps).forEach((app) => counts.set(app.icons, (counts.get(app.icons) ?? 0) + 1));

    return [...counts].sort(([a, x], [b, y]) => y - x || a.localeCompare(b))[0]?.[0] ?? "lucide";
};

const pascal = (name: string) => name.split("-").map((part) => part[0].toUpperCase() + part.slice(1)).join("");

/** Folder of an app's copy of an example (Next: a private folder next to its route page) */
const exampleDir = (app: AppFiles, example: string) =>
    app.next ? join(app.next.appDir, "tyohnn", example, "_example") : join(app.dir, "src/tyohnn", example);

/** An app that wears a theme other than its system's own gets this generated file next to its entry CSS. */
const appThemeCss = (app: AppFiles): string => join(dirname(app.css), "tyohnn-theme.css");

const planOwnedFiles = (ctx: SyncContext, placement: Placement, apps: AppFiles[]): OwnedFiles =>
{
    const { registry, record } = ctx;
    const owned = new OwnedFiles(ctx.root, record, ctx.changes, ctx.options.force);
    const copy = (from: string, to: string) => owned.plan(to, from, isCode(from) ? placement.rewrite(registry.read(from)) : registry.read(from));

    for (const file of registry.manifest.files)
    {
        if (!/^(components|hooks|lib)\//.test(file) && file !== "icons/names.ts") continue;

        copy(`registry/ui/${file}`, placement.target(`registry/ui/${file}`)!);
    }

    const libraries = usedIcons(record);
    const monorepoDefault = defaultIconLibrary(record);

    for (const library of libraries)
    {
        const from = `registry/ui/${registry.iconLibrary(library).file}`;

        copy(from, placement.target(from)!);
    }

    owned.plan(join(placement.iconsDir, "index.ts"), "generated:icons/index.ts", placement.monorepo
        ? [
            `// Generated by tyohnn. ${placement.iconSpecifier}: the default icon library of this package (${monorepoDefault}), which its own`,
            "// typecheck resolves. Each app's tsconfig `paths` points the specifier at the library that app uses.",
            `export * from "./libraries/${monorepoDefault}";`,
            "",
        ].join("\n")
        : [
            `// Generated by tyohnn: the app's icon library (${libraries[0]}). \`tyohnn icons <library>\` replaces it.`,
            `export * from "./libraries/${libraries[0]}";`,
            "",
        ].join("\n"));

    if (placement.monorepo)
    {
        owned.plan(join(placement.iconsDir, "check.ts"), "generated:icons/check.ts", [
            "// Generated by tyohnn. Type-level completeness: every installed library exports every semantic name.",
            ...libraries.map((name) => `import type * as ${name} from "./libraries/${name}";`),
            'import type { IconComponent, IconName } from "./names";',
            "",
            "type Complete<Library extends Record<IconName, IconComponent>> = Library;",
            "",
            "export type IconLibraries = {",
            ...libraries.map((name) => `    ${name}: Complete<typeof ${name}>;`),
            "};",
            "",
        ].join("\n"));
    }

    for (const system of usedSystems(record))
    {
        for (const file of registry.systemFiles(system))
        {
            const from = `${registry.systemDir(system)}/${file}`;

            copy(from, placement.target(from)!);
        }
    }

    for (const app of apps)
    {
        const appRecord = record.apps[app.path];

        if (!isOwnTheme(appRecord.theme, registry, appRecord.system))
        {
            owned.plan(appThemeCss(app), "generated:theme.css", themeCss(appRecord.theme!, ctx.root, registry));
        }
    }

    for (const app of apps)
    {
        const example = record.apps[app.path].example;

        if (!example) continue;

        const dir = exampleDir(app, example);

        for (const from of registry.templateFiles(example)) copy(from, join(dir, from.split("/").at(-1)!));

        if (app.next)
        {
            owned.plan(join(dir, "../page.tsx"), `generated:example-page/${example}`, [
                `import { ${pascal(example)} } from "./_example";`,
                "",
                "export default function Page()",
                "{",
                `    return <${pascal(example)} />;`,
                "}",
                "",
            ].join("\n"));
        }
    }

    return owned;
};

const syncPackages = (ctx: SyncContext, placement: Placement, apps: AppFiles[]): boolean =>
{
    const { registry, record, root } = ctx;
    const pm: PackageManager = record.packageManager;
    const iconPackages = (libraries: string[]) => Object.assign({}, ...libraries.map((library) => registry.iconLibrary(library).packages)) as Record<string, string>;
    const allIconPackages = new Set(Object.keys(iconPackages(Object.keys(registry.manifest.iconLibraries))));
    const allFontPackages = new Set([...registry.fonts().values()].flatMap((font) => [font.fontsource?.package, font.npm?.package].filter((name): name is string => Boolean(name))));
    const managed = new Set([...allIconPackages, ...allFontPackages]);
    let changed = false;

    const apply = (file: string, plan: { dependencies?: Record<string, string>; devDependencies?: Record<string, string> }, create?: PackageJson) =>
    {
        const key = rel(root, file);
        const result = syncDependencies(file, plan, record.packages[key] ?? [], managed, create);

        record.packages[key] = result.added;
        if (result.changed) ctx.changes.wrote(key);
        changed ||= result.changed;
    };

    const tailwind = (framework: "next" | "vite") => ({
        tailwindcss: TAILWIND_RANGE,
        [framework === "next" ? "@tailwindcss/postcss" : "@tailwindcss/vite"]: TAILWIND_RANGE,
    });

    if (placement.monorepo)
    {
        const uiDir = join(root, record.ui.path);
        const pkgFile = join(uiDir, "package.json");
        const exportsChanged = updatePackageJson(pkgFile, (pkg) =>
        {
            pkg.exports = {
                ...(pkg.exports as Record<string, string> | undefined),
                "./components/*": "./src/components/*.tsx",
                "./hooks/*": "./src/hooks/*.ts",
                "./lib/*": "./src/lib/*.ts",
                "./icons": "./src/icons/index.ts",
                "./icons/names": "./src/icons/names.ts",
                "./systems/*": "./src/systems/*",
            };
            pkg.scripts = { ...pkg.scripts, typecheck: pkg.scripts?.typecheck ?? "tsc --noEmit" };
        }, {
            name: record.ui.importBase,
            version: "0.0.0",
            private: true,
            description: "shadcn components on Base UI primitives with tyohnn design systems: one set of TSX, one CSS folder per system.",
        });

        if (exportsChanged) ctx.changes.wrote(rel(root, pkgFile));
        changed ||= exportsChanged;

        apply(pkgFile, {
            dependencies: { ...registry.manifest.dependencies, ...iconPackages(usedIcons(record)) },
            devDependencies: registry.manifest.devDependencies,
        });

        const tsconfig = join(uiDir, "tsconfig.json");

        if (!exists(tsconfig))
        {
            writeFile(tsconfig, `${JSON.stringify({
                compilerOptions: {
                    target: "ES2022",
                    lib: ["ES2022", "DOM", "DOM.Iterable"],
                    module: "esnext",
                    moduleResolution: "bundler",
                    jsx: "react-jsx",
                    strict: true,
                    noEmit: true,
                    skipLibCheck: true,
                    isolatedModules: true,
                    esModuleInterop: true,
                    resolveJsonModule: true,
                },
                include: ["src"],
                exclude: ["node_modules"],
            }, null, 4)}\n`);
            ctx.changes.wrote(rel(root, tsconfig));
        }

        for (const app of apps)
        {
            const appRecord = record.apps[app.path];

            apply(app.pkg, {
                dependencies: { [record.ui.importBase]: workspaceRange(pm), ...fontPackages(appRecord.fonts, registry, app.framework) },
                devDependencies: tailwind(app.framework),
            });
        }
    }
    else
    {
        const app = apps[0];
        const appRecord = record.apps[app.path];

        apply(app.pkg, {
            dependencies: { ...registry.manifest.dependencies, ...iconPackages(usedIcons(record)), ...fontPackages(appRecord.fonts, registry, app.framework) },
            devDependencies: { ...registry.manifest.devDependencies, ...tailwind(app.framework) },
        });
    }

    return changed;
};

/** Custom property names a system declares in layer 1 (globals and the generated theme) and layer 2 */
const systemTokenNames = (registry: Registry, system: string): Set<string> =>
    new Set(["globals.css", "theme.css", "tokens.css"].flatMap((file) => [...registry.read(`${registry.systemDir(system)}/styles/${file}`).matchAll(/(--[A-Za-z0-9_-]+)\s*:/g)].map((match) => match[1])));

const wireApp = (ctx: SyncContext, placement: Placement, app: AppFiles) =>
{
    const { registry, record, root, changes } = ctx;
    const appRecord: AppRecord = record.apps[app.path];
    const system = appRecord.system;
    const cssDir = dirname(app.css);
    const edit = (file: string, transform: (content: string) => { code: string; manual?: string } | string, create?: string) =>
    {
        const before = readIfExists(file);

        if (before === null && create === undefined) return;

        const result = transform(before ?? create!);
        const code = typeof result === "string" ? result : result.code;

        if (typeof result !== "string" && result.manual) changes.warn(`by hand: ${result.manual}`);
        if (writeFile(file, code)) changes.wrote(rel(root, file));
    };

    // Entry CSS
    const systemSpecifier = placement.monorepo ? `${record.ui.importBase}/systems/${system}` : relSpecifier(cssDir, placement.systemDir(system));
    const systemBlock = [
        `/* Design system ${system} (tyohnn). One system per app; this order is the cascade contract: tailwindcss → layer 1`,
        "   globals → layer 1 theme colours → layer 2 tokens → typeset → layer 3 rules in layer(base), so className utilities still win. */",
        '@import "tailwindcss";',
        ...(app.framework === "vite" ? cssFontImports(appRecord.fonts, registry) : []),
        ...SYSTEM_CSS_FILES.map((file) =>
        {
            // The app's own colours replace the system's, in the same place in the cascade.
            if (file === "theme.css" && !isOwnTheme(appRecord.theme, registry, system)) return `@import "${relSpecifier(cssDir, appThemeCss(app))}";`;

            return `@import "${systemSpecifier}/${file}"${file === "style.css" ? " layer(base)" : ""};`;
        }),
    ].join("\n");

    const system_ = registry.system(system);
    const stacks = app.framework === "next"
        ? nextFontStacks(appRecord.fonts, registry)
        : sameFonts(system_.fonts, appRecord.fonts) ? null : familyStacks(appRecord.fonts, registry);
    const themeBlock = [
        ...(placement.monorepo
            ? [
                "/* Tailwind does not scan workspace packages by itself; the system folders hold CSS, not class names. */",
                `@source "${relSpecifier(cssDir, placement.base)}";`,
                `@source not "${relSpecifier(cssDir, join(placement.base, "systems"))}";`,
            ]
            : [`@source not "${relSpecifier(cssDir, join(placement.base, "styles/tyohnn"))}";`]),
        ...(stacks
            ? [
                "",
                app.framework === "next"
                    ? "/* Font stacks on the next/font variables of the root layout (next/font registers its own family names). */"
                    : `/* Font stacks for ${[appRecord.fonts.sans, appRecord.fonts.heading, appRecord.fonts.mono].join(" · ")} (the system's own name ${[system_.fonts.sans, system_.fonts.heading, system_.fonts.mono].join(" · ")}). */`,
                stacksCss(stacks),
            ]
            : []),
    ].join("\n");

    edit(app.css, (content) => applyEntryCss(content, { system: systemBlock, theme: themeBlock }), "");

    const shadowed = userCustomProperties(read(app.css)).filter((name) => systemTokenNames(registry, system).has(name));

    if (shadowed.length)
    {
        changes.warn(`${rel(root, app.css)} declares ${shadowed.slice(0, 4).join(", ")}${shadowed.length > 4 ? ` and ${shadowed.length - 4} more` : ""} outside the tyohnn blocks: these override ${system}'s values (remove them to get the system as designed)`);
    }

    const cssSpecifier = app.cssImporter ? relSpecifier(dirname(app.cssImporter), app.css) : null;

    // tsconfig paths
    const pathEntries: Record<string, string[]> = {};

    if (placement.monorepo)
    {
        pathEntries[placement.iconSpecifier] = [relSpecifier(app.dir, join(placement.librariesDir, `${appRecord.icons}.tsx`))];
    }
    else
    {
        pathEntries[`${record.ui.importBase}/*`] = [`${relSpecifier(app.dir, placement.base)}/*`];
    }

    for (const tsconfig of app.tsconfigs)
    {
        const inherited = effectivePaths(tsconfig);
        const existing = readIfExists(tsconfig);
        const wanted = placement.monorepo ? pathEntries : Object.fromEntries(Object.entries(pathEntries).filter(([key]) => !inherited?.paths[key]));

        if (existing === null)
        {
            if (tsconfig !== app.tsconfigs[0]) continue;
            changes.warn(`${rel(root, tsconfig)} does not exist: create it with compilerOptions.paths ${JSON.stringify(pathEntries)}`);
            continue;
        }

        if (Object.keys(wanted).length === 0) continue;

        edit(tsconfig, (content) => setPaths(content, wanted, inherited && inherited.from !== tsconfig ? { paths: inherited.paths, fromDir: dirname(inherited.from), toDir: dirname(tsconfig) } : undefined));
    }

    if (app.next)
    {
        // postcss
        if (!app.next.postcss)
        {
            writeFile(join(app.dir, "postcss.config.mjs"), 'export default { plugins: { "@tailwindcss/postcss": {} } };\n');
            changes.wrote(rel(root, join(app.dir, "postcss.config.mjs")));
        }
        else if (!read(app.next.postcss).includes("@tailwindcss/postcss"))
        {
            changes.warn(`by hand: add the "@tailwindcss/postcss" plugin to ${rel(root, app.next.postcss)}`);
        }

        // layout
        const layout = app.next.layout ?? join(app.next.appDir, "layout.tsx");
        const font = nextFontCode(appRecord.fonts, registry, dirname(layout), (name) => packageDir(app.dir, name, root), (name) => expectedPackageDir(app.dir, name, root, record.packageManager));
        const htmlClasses = [...(appRecord.mode === "dark" ? ['"dark"'] : []), '"font-sans"', ...font.variables];
        const body = layoutBlock([
            `// Fonts of ${system}: ${[appRecord.fonts.sans, appRecord.fonts.heading, appRecord.fonts.mono, appRecord.fonts.hangulFallback].join(" · ")} (sans · heading · mono · hangul), self-hosted by next/font.`,
            ...font.lines,
        ], htmlClasses);
        const blockWithMode = body.replace(`const ${HTML_CLASS_IDENTIFIER}`, `// <html>: ${appRecord.mode} mode${appRecord.mode === "dark" ? " (`dark` belongs on <html>: layer-2 values resolve on :root)" : ""} · font-sans · next/font variables\nconst ${HTML_CLASS_IDENTIFIER}`);
        const newLayout = [
            'import type { Metadata } from "next";',
            'import type { ReactNode } from "react";',
            "",
            `export const metadata: Metadata = { title: ${JSON.stringify(app.path === "." ? "App" : app.path.split("/").at(-1))} };`,
            "",
            "export default function RootLayout({ children }: Readonly<{ children: ReactNode }>)",
            "{",
            "    return (",
            '        <html lang="en">',
            "            <body>{children}</body>",
            "        </html>",
            "    );",
            "}",
            "",
        ].join("\n");

        edit(layout, (content) => applyLayout(content, blockWithMode, cssSpecifier ?? relSpecifier(dirname(layout), app.css), rel(root, layout)), newLayout);

        if (font.unresolved.length) changes.warn(`${font.unresolved.join(", ")} not installed in the project yet: ${rel(root, layout)} points next/font/local at ${font.unresolved.map((name) => rel(root, expectedPackageDir(app.dir, name, root, record.packageManager))).join(", ")} without having seen the files there (run the command again after installing to verify)`);

        // next.config
        if (placement.monorepo)
        {
            const config = app.next.config ?? join(app.dir, "next.config.ts");

            edit(config, (content) => ensureTranspilePackage(content, record.ui.importBase, rel(root, config)), newNextConfig(record.ui.importBase));
        }
    }

    if (app.vite)
    {
        if (app.cssImporter) edit(app.cssImporter, (content) => ensureCssImport(content, relSpecifier(dirname(app.cssImporter!), app.css), rel(root, app.cssImporter!)));
        else changes.warn(`by hand: import ${rel(root, app.css)} from the app's entry module`);

        edit(app.vite.indexHtml, (content) => applyIndexHtml(content, appRecord.mode));

        const aliases: ViteAlias[] = placement.monorepo
            ? [{ find: placement.iconSpecifier, exact: true, target: relSpecifier(app.dir, join(placement.librariesDir, `${appRecord.icons}.tsx`)) }]
            : [{ find: record.ui.importBase, exact: false, target: relSpecifier(app.dir, placement.base) }];
        const config = app.vite.config ?? join(app.dir, "vite.config.ts");

        edit(config, (content) => applyViteConfig(content, aliases, rel(root, config)), 'import { defineConfig } from "vite";\n\nexport default defineConfig({});\n');
    }

    appRecord.css = rel(root, app.css);
};

export const sync = async (ctx: SyncContext): Promise<void> =>
{
    const { root, record } = ctx;
    const placement = placementOf(root, record);
    const apps = Object.keys(record.apps).sort().map((path) => inspectApp(root, path));

    // Validate choices before writing anything.
    for (const app of Object.values(record.apps))
    {
        ctx.registry.system(app.system);
        ctx.registry.iconLibrary(app.icons);
    }

    const owned = planOwnedFiles(ctx, placement, apps);

    owned.assertNoConflicts();
    owned.write();
    owned.prune();

    record.ui.systems = usedSystems(record);
    record.ui.icons = usedIcons(record);

    const packagesChanged = syncPackages(ctx, placement, apps);
    const installed = exists(join(root, "node_modules"));

    if (ctx.options.install && (packagesChanged || !installed)) await install(root, record.packageManager);
    else if (packagesChanged) ctx.changes.note(`dependencies changed: run \`${record.packageManager} install\``);

    for (const app of apps) wireApp(ctx, placement, app);

    if (writeRecord(root, record)) ctx.changes.wrote("tyohnn.json");
};
