// compose(themeName) — writes dist/themes/<name>/index.css (an entry made of imports) and compiles it
// with the Tailwind CLI into dist/themes/<name>/compiled.css.
//
// Usage: node tooling/compose-theme <name>… | --all  [--no-compile]

import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import { composeOrder, listThemes, repoRoot } from "./registry.mjs";

const require = createRequire(import.meta.url);

/** Folders Tailwind scans for utility class names */
export const SOURCES = [
    join(repoRoot, "registry/ui/components"),
    join(repoRoot, "apps/preview/src"),
    join(repoRoot, "apps/preview/index.html"),
];

export const distDir = (name) => join(repoRoot, "dist/themes", name);

const rel = (from, file) =>
{
    const path = relative(from, file).split("\\").join("/");

    return path.startsWith(".") ? path : `./${path}`;
};

export const renderEntry = (name) =>
{
    const out = distDir(name);
    const order = composeOrder(name);
    const line = (file, suffix = "") => `@import "${rel(out, file)}"${suffix};`;

    return [
        `/* Generated by tooling/compose-theme — do not edit. Theme: ${order.chain.join(" → ")} */`,
        "",
        "/* Tailwind (scanning is explicit, see @source below) */",
        `@import "tailwindcss" source(none);`,
        "",
        "/* Layer 1 — colours: foundation, then overrides */",
        ...order.colors.map((file) => line(file)),
        "",
        "/* Layer 2 — tokens: foundation, then overrides */",
        ...order.tokens.map((file) => line(file)),
        "",
        "/* Long-form typesetting */",
        ...order.typeset.map((file) => line(file)),
        "",
        "/* Layer 3 — foundation barrel, theme replacements substituted in place */",
        ...order.rules.map((file) => line(file, " layer(base)")),
        "",
        "/* Layer 3 — theme additions */",
        ...order.additions.map((file) => line(file, " layer(base)")),
        "",
        ...SOURCES.map((source) => `@source "${rel(out, source)}";`),
        "",
    ].join("\n");
};

export const compose = (name, { compile = true } = {}) =>
{
    const out = distDir(name);
    const entry = join(out, "index.css");
    const compiled = join(out, "compiled.css");

    mkdirSync(out, { recursive: true });
    writeFileSync(entry, renderEntry(name));

    if (compile)
    {
        const cli = join(dirname(require.resolve("@tailwindcss/cli/package.json")), "dist/index.mjs");

        execFileSync(process.execPath, [cli, "--input", entry, "--output", compiled, "--optimize"], { cwd: repoRoot, stdio: ["ignore", "ignore", "pipe"] });
    }

    return { entry, compiled: compile ? compiled : null };
};

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === require.resolve(process.argv[1]);

if (isMain)
{
    const args = process.argv.slice(2);
    const compile = !args.includes("--no-compile");
    const names = args.includes("--all") ? listThemes() : args.filter((arg) => !arg.startsWith("--"));

    if (names.length === 0)
    {
        console.error("usage: node tooling/compose-theme <name>… | --all [--no-compile]");
        process.exit(2);
    }

    for (const name of names)
    {
        const result = compose(name, { compile });

        console.log(`${name}: ${relative(repoRoot, result.compiled ?? result.entry)}`);
    }
}
