// Generated by tyohnn scaffold-prototype — icons. Edit the registry and re-run instead of editing here.
// Type-level completeness: every installed library exports every semantic name as an icon component.
import type * as hugeicons from "./libraries/hugeicons";
import type * as lucide from "./libraries/lucide";
import type { IconComponent, IconName } from "./names";

type Complete<Library extends Record<IconName, IconComponent>> = Library;

export type IconLibraries = {
    hugeicons: Complete<typeof hugeicons>;
    lucide: Complete<typeof lucide>;
};
