// Generated by tyohnn. Type-level completeness: every installed library exports every semantic name.
import type * as hugeicons from "./libraries/hugeicons";
import type * as lucide from "./libraries/lucide";
import type { IconComponent, IconName } from "./names";

type Complete<Library extends Record<IconName, IconComponent>> = Library;

export type IconLibraries = {
    hugeicons: Complete<typeof hugeicons>;
    lucide: Complete<typeof lucide>;
};
