// Generated by tyohnn scaffold-prototype — icons. Edit the registry and re-run instead of editing here.
// @acme/ui/icons — the monorepo default icon library (lucide): what packages/ui's own tsc resolves.
// Each app points the specifier at its own libraries/<library>.tsx (tsconfig paths + next.config resolve aliases).
export * from "./libraries/lucide";
