// Generated by tyohnn. @acme/ui/icons: the default icon library of this package (hugeicons), which its own
// typecheck resolves. Each app's tsconfig `paths` points the specifier at the library that app uses.
export * from "./libraries/hugeicons";
