// build-system — compile one design system for the preview.
//
//   dist/systems/<name>/index.css     the entry (imports only)
//   dist/systems/<name>/compiled.css  Tailwind CLI output
//
// Fixed order: tailwindcss → globals (layer 1) → tokens (layer 2) → typeset → style.css in layer(base).
// Tailwind scans registry/ui and apps/preview only.
//
// Usage: node tooling/build-system <name>… | --all   (`foundation` is a valid name; --all includes it)

import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import { listSystems, repoRoot, styleFiles, systemRoot } from "./registry.mjs";

const require = createRequire(import.meta.url);

export const SOURCES = [
    join(repoRoot, "registry/ui"),
    join(repoRoot, "apps/preview/src"),
    join(repoRoot, "apps/preview/index.html"),
];

export const distDir = (name) => join(repoRoot, "dist/systems", name);

const rel = (from, file) =>
{
    const path = relative(from, file).split("\\").join("/");

    return path.startsWith(".") ? path : `./${path}`;
};

export const renderEntry = (name) =>
{
    const out = distDir(name);
    const files = styleFiles(systemRoot(name));

    return [
        `/* Generated by tooling/build-system — do not edit. System: ${name} */`,
        `@import "tailwindcss" source(none);`,
        `@import "${rel(out, files.colors)}";`,
        `@import "${rel(out, files.tokens)}";`,
        ...files.typeset.map((file) => `@import "${rel(out, file)}";`),
        `@import "${rel(out, files.barrel)}" layer(base);`,
        "",
        ...SOURCES.map((source) => `@source "${rel(out, source)}";`),
        "",
    ].join("\n");
};

export const buildSystem = (name) =>
{
    const out = distDir(name);
    const entry = join(out, "index.css");
    const compiled = join(out, "compiled.css");
    const cli = join(dirname(require.resolve("@tailwindcss/cli/package.json")), "dist/index.mjs");

    mkdirSync(out, { recursive: true });
    writeFileSync(entry, renderEntry(name));
    execFileSync(process.execPath, [cli, "--input", entry, "--output", compiled, "--optimize"], { cwd: repoRoot, stdio: ["ignore", "ignore", "pipe"] });

    return compiled;
};

if (process.argv[1] && fileURLToPath(import.meta.url) === require.resolve(process.argv[1]))
{
    const args = process.argv.slice(2);
    const names = args.includes("--all") ? ["foundation", ...listSystems()] : args.filter((arg) => !arg.startsWith("--"));

    if (names.length === 0)
    {
        console.error("usage: node tooling/build-system <name>… | --all");
        process.exit(2);
    }

    for (const name of names)
    {
        console.log(`${name}: ${relative(repoRoot, buildSystem(name))}`);
    }
}
